$axure.loadCurrentPage({
  "url":"page2.html",
  "generationDate":new Date(1422951640230.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"09e94be123d04c8d87dffc127322c479",
    "type":"Axure:Page",
    "name":"Page2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"00ff86f8f1aa463ab5867c67c0ab7d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":180},
            "size":{
              "width":1349,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc2912e9008844e59ef9c405953484e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":1349,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page2/u0.png"}},
{
          "id":"92ea50827c7745e5ac0e75dd86269b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":210},
            "size":{
              "width":160,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89339c7c6c284baeb9c1c7eaee28c162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":210},
                "size":{
                  "width":160,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page1",
                      "target":{
                        "targetType":"page",
                        "url":"page1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page1/u12.png"}},
{
          "id":"f8cf0462c3d34a5bbef4f65ae168188d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":563.5,
              "y":201},
            "size":{
              "width":160,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c450134be79540f6b565302341e55669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":563.5,
                  "y":201},
                "size":{
                  "width":160,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"当前步骤高亮"},
          "images":{
            "normal~":"images/page2/u4.png"}},
{
          "id":"2ada39a1073a4ca3b72bfc3903abd8ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":834,
              "y":210},
            "size":{
              "width":160,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfc02eedbcc94b85b7e5adbba90c509f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":834,
                  "y":210},
                "size":{
                  "width":160,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u12.png"}},
{
          "id":"93f434dc8c6745dbaab98ffb226cc0be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":192.5,
              "y":90},
            "size":{
              "width":903,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d117a1991b6b4696be80244b49ee25db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192.5,
                  "y":90},
                "size":{
                  "width":903,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b651a3590f04cc08112473487820027",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":241},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/page1/u66_end.png",
            "line~":"images/page1/u66_line.png"}},
{
          "id":"8728af338747421195d79a814429a103",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":241},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/page1/u66_end.png",
            "line~":"images/page1/u66_line.png"}},
{
          "id":"b6e6199443c24417bec84884b0355f4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1349,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6e699f5332145e3837cc58ce6343b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1349,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u2.png"}},
{
          "id":"88206b3532ed422597911d6327978ff4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":340,
              "y":0},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed1846682b5640d1a8d0401010a0d66e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":340,
                  "y":0},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3181c033d8d34fb6a0239ebedcaabb8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":670},
            "size":{
              "width":1330,
              "height":2364}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2bde5827c814a5d91fdc04fe368b0e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":670},
                "size":{
                  "width":1330,
                  "height":2364}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u8.png"}},
{
          "id":"d8cd6e8c8fe04c15bc50f9bc56acc530",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":60},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6379b94279d47d6abb8a915454b604d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1190,
                  "y":60},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u62.png"}},
{
          "id":"9f25a4e5d3cd4368bf63d0a0199059bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1202,
              "y":160},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c0fab0115b48a19835f1b0e0e4412a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1202,
                  "y":160},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1a204cd346542248ce4b667c9a6eec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":319},
            "size":{
              "width":391,
              "height":219}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea27fdff17644a90a92f26b1d02de4e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":319},
                "size":{
                  "width":391,
                  "height":219}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page2/u22.png"}},
{
          "id":"d36f717a5eff45339f222aece15b9f64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":579},
            "size":{
              "width":166,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea11c9d6ab94053bcb882dac1ad3d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":579},
                "size":{
                  "width":166,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 success",
                      "target":{
                        "targetType":"page",
                        "url":"success.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page2/u24.png"}},
{
          "id":"24b660b66aa14b3ea7562c499e2e047b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}}},
            "location":{
              "x":420,
              "y":579},
            "size":{
              "width":100,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f102ca10514e29967a190d65080b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}}},
                "location":{
                  "x":420,
                  "y":579},
                "size":{
                  "width":100,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page1",
                      "target":{
                        "targetType":"page",
                        "url":"page1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page2/u26.png",
            "mouseOver~":"images/page2/u26.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "00ff86f8f1aa463ab5867c67c0ab7d6d":{
      "scriptId":"u0"},
    "dc2912e9008844e59ef9c405953484e9":{
      "scriptId":"u1"},
    "92ea50827c7745e5ac0e75dd86269b55":{
      "scriptId":"u2"},
    "89339c7c6c284baeb9c1c7eaee28c162":{
      "scriptId":"u3"},
    "f8cf0462c3d34a5bbef4f65ae168188d":{
      "scriptId":"u4"},
    "c450134be79540f6b565302341e55669":{
      "scriptId":"u5"},
    "2ada39a1073a4ca3b72bfc3903abd8ad":{
      "scriptId":"u6"},
    "bfc02eedbcc94b85b7e5adbba90c509f":{
      "scriptId":"u7"},
    "93f434dc8c6745dbaab98ffb226cc0be":{
      "scriptId":"u8"},
    "d117a1991b6b4696be80244b49ee25db":{
      "scriptId":"u9"},
    "2b651a3590f04cc08112473487820027":{
      "scriptId":"u10"},
    "8728af338747421195d79a814429a103":{
      "scriptId":"u11"},
    "b6e6199443c24417bec84884b0355f4a":{
      "scriptId":"u12"},
    "a6e699f5332145e3837cc58ce6343b5f":{
      "scriptId":"u13"},
    "88206b3532ed422597911d6327978ff4":{
      "scriptId":"u14"},
    "ed1846682b5640d1a8d0401010a0d66e":{
      "scriptId":"u15"},
    "3181c033d8d34fb6a0239ebedcaabb8c":{
      "scriptId":"u16"},
    "f2bde5827c814a5d91fdc04fe368b0e5":{
      "scriptId":"u17"},
    "d8cd6e8c8fe04c15bc50f9bc56acc530":{
      "scriptId":"u18"},
    "c6379b94279d47d6abb8a915454b604d":{
      "scriptId":"u19"},
    "9f25a4e5d3cd4368bf63d0a0199059bb":{
      "scriptId":"u20"},
    "66c0fab0115b48a19835f1b0e0e4412a":{
      "scriptId":"u21"},
    "d1a204cd346542248ce4b667c9a6eec7":{
      "scriptId":"u22"},
    "ea27fdff17644a90a92f26b1d02de4e2":{
      "scriptId":"u23"},
    "d36f717a5eff45339f222aece15b9f64":{
      "scriptId":"u24"},
    "cea11c9d6ab94053bcb882dac1ad3d74":{
      "scriptId":"u25"},
    "24b660b66aa14b3ea7562c499e2e047b":{
      "scriptId":"u26"},
    "d7f102ca10514e29967a190d65080b78":{
      "scriptId":"u27"}}});