$axure.loadCurrentPage({
  "url":"page1.html",
  "generationDate":new Date(1422951640011.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"216ee0795b6349ff931041ebe531b98a",
    "type":"Axure:Page",
    "name":"Page1",
    "notes":{
      "默认":"<p><span>在顶部显示部分数据，说明搜房值得信赖</span></p><p><span>右侧有APP二维码，提示用户下载APP</span></p><p><span>&nbsp;</span></p><p><span>简化操作</span><span>：</span></p><p><span>将原来的三步变为两步</span><span>；</span></p><p><span>配有流程图，是用户更清晰，突出发房源步骤简单。</span></p><p><span>删除部分字段（楼栋/房号）</span><span>；</span><span></span></p><p><span>将原来</span><span>部分的输入框（户型）改为下拉框，简化操作；</span></p><p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0725f3e4c2ec454d8d81a96d325dab81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":180},
            "size":{
              "width":1349,
              "height":466}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85957283032b4887b3569a7f3708b65b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":1349,
                  "height":466}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u0.png"}},
{
          "id":"4d5950c4877d432880c0fd55191f9130",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1349,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6e454d932224ecb89f257c54f9ab252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1349,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u2.png"}},
{
          "id":"b04ca3d23fed4197a1b3cc1ca8c897f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":594},
            "size":{
              "width":149,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97544a9c63bc4a9494bdf7772a42423f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":594},
                "size":{
                  "width":149,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Page2",
                      "target":{
                        "targetType":"page",
                        "url":"page2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page1/u4.png"}},
{
          "id":"e43be9a585ab40568d9d53caa2f28dc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":340,
              "y":0},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc6c60b6b8dd4fbbae0da80b926861a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":340,
                  "y":0},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d432f9c442584e9197fb11d69d1460c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":660},
            "size":{
              "width":1330,
              "height":2364}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd94572806de4f399ae4db418a23f48e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":660},
                "size":{
                  "width":1330,
                  "height":2364}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u8.png"}},
{
          "id":"3c2a1c78ef614dbd88e841790f81e245",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":201},
            "size":{
              "width":160,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCFFFF},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d007395cb740d59ef30977a28bdb81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":201},
                "size":{
                  "width":160,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"当前步骤高亮"},
          "images":{
            "normal~":"images/page1/u10.png"}},
{
          "id":"41b9dd8d32f340e6a95631c00a135731",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":564,
              "y":210},
            "size":{
              "width":160,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1689f49fdb904e298630e4bd7d139c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":564,
                  "y":210},
                "size":{
                  "width":160,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u12.png"}},
{
          "id":"c3532483e79d408bb0d5cc2e3e24e3e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":834,
              "y":210},
            "size":{
              "width":160,
              "height":72},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":255,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22adc14ef431400c99b27c05c3c30abd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":834,
                  "y":210},
                "size":{
                  "width":160,
                  "height":72},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":255,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u12.png"}},
{
          "id":"5b4404aba6f84ff3802bfb117eb09706",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":379},
            "size":{
              "width":60,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"21858b8396cf44b2938a74cead402210",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":379},
            "size":{
              "width":60,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"f75375bebfc14c98b7be1765972a64dc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":379},
            "size":{
              "width":60,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"906c3e76412e435e8f90bcd0e7225bfa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":422},
            "size":{
              "width":244,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b51f849f4ffa4e4baaea283605ae0ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":422},
                "size":{
                  "width":244,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u19.png"}},
{
          "id":"0fbba0bb54694bd2b198e641d43aeaa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":682,
              "y":432},
            "size":{
              "width":220,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a6f16ecb1d4840a537ddcaa85a43da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":682,
                  "y":432},
                "size":{
                  "width":220,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u21.png"}},
{
          "id":"095127ee6faf4a4ea7bc342bb00f890f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":688,
              "y":435},
            "size":{
              "width":194,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5f9849b759e438690a7cdae923bf8ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":688,
                  "y":435},
                "size":{
                  "width":194,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab38a429ca874eeb8b0733bedb6a2398",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}}},
            "location":{
              "x":686,
              "y":451},
            "size":{
              "width":182,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be905eafa2dc4e01a9861040e07f23d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}}},
                "location":{
                  "x":686,
                  "y":451},
                "size":{
                  "width":182,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 update",
                      "target":{
                        "targetType":"page",
                        "url":"update.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page1/u25.png",
            "mouseOver~":"images/page1/u25.png"}},
{
          "id":"6984e7a6bcdb4ae495a67bfcb8170a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1}}},
            "location":{
              "x":686,
              "y":471},
            "size":{
              "width":216,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4006551ceb14098baa09ec7456e1a0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1}}},
                "location":{
                  "x":686,
                  "y":471},
                "size":{
                  "width":216,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 house",
                      "target":{
                        "targetType":"page",
                        "url":"house.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page1/u27.png",
            "mouseOver~":"images/page1/u27.png"}},
{
          "id":"ba01a27974e3455c8da2c8b78ce80202",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":367,
              "y":329},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b081014e60427fae015d1ccb84b2e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":367,
                  "y":329},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"454f2840b4c7436a952db67ce1de66b9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":444,
              "y":325},
            "size":{
              "width":297,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"9f28e16fd5ac48ba8d9d7a48d18d79fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":335},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"401b300237d3428ba375a2f5b6e07045",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":335},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u32.gif"}},
{
          "id":"e151ff5ead0c42e795f6d0bdd86952bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":777,
              "y":317},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e73ba15f4b4456af28d64306aff3d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":777,
                  "y":317},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u34.png"}},
{
          "id":"643204b75e5d4c19a9a8eb5c7651dab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":394,
              "y":387},
            "size":{
              "width":38,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f7a1f26ff14980bf26faad817c771c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":394,
                  "y":387},
                "size":{
                  "width":38,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e34e1f4f75c48068d509ce72f695f8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":517,
              "y":389},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ae47942cf24110a2356998be95d3c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":517,
                  "y":389},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f2beec0aa3f4566aca04e1f285f67c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":612,
              "y":389},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7b4124901994effb423ab9dd8dc1cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":612,
                  "y":389},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a41f8a051bb4f8889d2e38dd7407e3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":709,
              "y":389},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c0ec5d8c16b458aa9531f9dd0a31aaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":709,
                  "y":389},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40c7ccdd392a459988adc27dae3cc50b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":734,
              "y":390},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22242468686347d9ae82e6a72b6b057d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":734,
                  "y":390},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u32.gif"}},
{
          "id":"077349d1fe0e4980990dca067c7d6f2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":394,
              "y":438},
            "size":{
              "width":38,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cff533063cf1460398dd8d3ec371280b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":394,
                  "y":438},
                "size":{
                  "width":38,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7001856d891144b9a0401b45fdec7acd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":444,
              "y":431},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"ff902129126d4f02ade5b23f291a29b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":584,
              "y":439},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdfcb991634440d489056364997c5608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":584,
                  "y":439},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f77a931d99c642a38cea30e5590a3200",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":442},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a5538bdd92f45ab973b2167a96cd068",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":637,
                  "y":442},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u32.gif"}},
{
          "id":"7daea259cfa64e37b69c8ed447b2e3b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":367,
              "y":487},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a3580ed2174212abd5a7542f5f8bbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":367,
                  "y":487},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f69558ff9ab0450fa2c8c26142579b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":192.5,
              "y":90},
            "size":{
              "width":903,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f35c0ab6451a4a4aa69aceda47f638ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192.5,
                  "y":90},
                "size":{
                  "width":903,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"此数据并不够，更希望是：10000位用户在搜房成交，平均成交时间72小时（不知能否得到数据）"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c92ade22047f4affb43c379a3d796168",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":444,
              "y":480},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"51a0b6f1d33b465bb557690c871d36b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":491},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f99d1084102c4875aad62d37693b9679",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":491},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u32.gif"}},
{
          "id":"96934760bcb24d23b3e8fc1056759654",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":565,
              "y":485},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e03ffc86b82463a942cacb0f1fec34b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":565,
                  "y":485},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"603a4b206ada400ab7e386d28d133341",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":60},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1288a2f09744491db3de5319625402a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1180,
                  "y":60},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u62.png"}},
{
          "id":"0ab1d9a70501412fa94c5eeb0890c69d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1192,
              "y":160},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc190017f256495ab82bdd053dc4eb15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1192,
                  "y":160},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ca535da749649aaa63a729d58404eda",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":241},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/page1/u66_end.png",
            "line~":"images/page1/u66_line.png"}},
{
          "id":"06804e2687344ac98c0e947302b12008",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":241},
            "size":{
              "width":110,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/page1/u66_end.png",
            "line~":"images/page1/u66_line.png"}},
{
          "id":"cbc429bcce944dc98ed5aec001d78b30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":520},
            "size":{
              "width":556,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b01452bc9a794c68898ac4612d8db70f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":520},
                "size":{
                  "width":556,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u68.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0725f3e4c2ec454d8d81a96d325dab81":{
      "scriptId":"u0"},
    "85957283032b4887b3569a7f3708b65b":{
      "scriptId":"u1"},
    "4d5950c4877d432880c0fd55191f9130":{
      "scriptId":"u2"},
    "f6e454d932224ecb89f257c54f9ab252":{
      "scriptId":"u3"},
    "b04ca3d23fed4197a1b3cc1ca8c897f8":{
      "scriptId":"u4"},
    "97544a9c63bc4a9494bdf7772a42423f":{
      "scriptId":"u5"},
    "e43be9a585ab40568d9d53caa2f28dc7":{
      "scriptId":"u6"},
    "bc6c60b6b8dd4fbbae0da80b926861a6":{
      "scriptId":"u7"},
    "d432f9c442584e9197fb11d69d1460c6":{
      "scriptId":"u8"},
    "cd94572806de4f399ae4db418a23f48e":{
      "scriptId":"u9"},
    "3c2a1c78ef614dbd88e841790f81e245":{
      "scriptId":"u10"},
    "06d007395cb740d59ef30977a28bdb81":{
      "scriptId":"u11"},
    "41b9dd8d32f340e6a95631c00a135731":{
      "scriptId":"u12"},
    "1689f49fdb904e298630e4bd7d139c19":{
      "scriptId":"u13"},
    "c3532483e79d408bb0d5cc2e3e24e3e5":{
      "scriptId":"u14"},
    "22adc14ef431400c99b27c05c3c30abd":{
      "scriptId":"u15"},
    "5b4404aba6f84ff3802bfb117eb09706":{
      "scriptId":"u16"},
    "21858b8396cf44b2938a74cead402210":{
      "scriptId":"u17"},
    "f75375bebfc14c98b7be1765972a64dc":{
      "scriptId":"u18"},
    "906c3e76412e435e8f90bcd0e7225bfa":{
      "scriptId":"u19"},
    "b51f849f4ffa4e4baaea283605ae0ef6":{
      "scriptId":"u20"},
    "0fbba0bb54694bd2b198e641d43aeaa9":{
      "scriptId":"u21"},
    "07a6f16ecb1d4840a537ddcaa85a43da":{
      "scriptId":"u22"},
    "095127ee6faf4a4ea7bc342bb00f890f":{
      "scriptId":"u23"},
    "e5f9849b759e438690a7cdae923bf8ba":{
      "scriptId":"u24"},
    "ab38a429ca874eeb8b0733bedb6a2398":{
      "scriptId":"u25"},
    "be905eafa2dc4e01a9861040e07f23d4":{
      "scriptId":"u26"},
    "6984e7a6bcdb4ae495a67bfcb8170a8b":{
      "scriptId":"u27"},
    "d4006551ceb14098baa09ec7456e1a0b":{
      "scriptId":"u28"},
    "ba01a27974e3455c8da2c8b78ce80202":{
      "scriptId":"u29"},
    "87b081014e60427fae015d1ccb84b2e2":{
      "scriptId":"u30"},
    "454f2840b4c7436a952db67ce1de66b9":{
      "scriptId":"u31"},
    "9f28e16fd5ac48ba8d9d7a48d18d79fd":{
      "scriptId":"u32"},
    "401b300237d3428ba375a2f5b6e07045":{
      "scriptId":"u33"},
    "e151ff5ead0c42e795f6d0bdd86952bd":{
      "scriptId":"u34"},
    "d9e73ba15f4b4456af28d64306aff3d4":{
      "scriptId":"u35"},
    "643204b75e5d4c19a9a8eb5c7651dab3":{
      "scriptId":"u36"},
    "92f7a1f26ff14980bf26faad817c771c":{
      "scriptId":"u37"},
    "9e34e1f4f75c48068d509ce72f695f8d":{
      "scriptId":"u38"},
    "b1ae47942cf24110a2356998be95d3c7":{
      "scriptId":"u39"},
    "8f2beec0aa3f4566aca04e1f285f67c3":{
      "scriptId":"u40"},
    "b7b4124901994effb423ab9dd8dc1cb0":{
      "scriptId":"u41"},
    "4a41f8a051bb4f8889d2e38dd7407e3b":{
      "scriptId":"u42"},
    "5c0ec5d8c16b458aa9531f9dd0a31aaf":{
      "scriptId":"u43"},
    "40c7ccdd392a459988adc27dae3cc50b":{
      "scriptId":"u44"},
    "22242468686347d9ae82e6a72b6b057d":{
      "scriptId":"u45"},
    "077349d1fe0e4980990dca067c7d6f2f":{
      "scriptId":"u46"},
    "cff533063cf1460398dd8d3ec371280b":{
      "scriptId":"u47"},
    "7001856d891144b9a0401b45fdec7acd":{
      "scriptId":"u48"},
    "ff902129126d4f02ade5b23f291a29b5":{
      "scriptId":"u49"},
    "cdfcb991634440d489056364997c5608":{
      "scriptId":"u50"},
    "f77a931d99c642a38cea30e5590a3200":{
      "scriptId":"u51"},
    "3a5538bdd92f45ab973b2167a96cd068":{
      "scriptId":"u52"},
    "7daea259cfa64e37b69c8ed447b2e3b7":{
      "scriptId":"u53"},
    "f4a3580ed2174212abd5a7542f5f8bbf":{
      "scriptId":"u54"},
    "f69558ff9ab0450fa2c8c26142579b7c":{
      "scriptId":"u55"},
    "f35c0ab6451a4a4aa69aceda47f638ba":{
      "scriptId":"u56"},
    "c92ade22047f4affb43c379a3d796168":{
      "scriptId":"u57"},
    "51a0b6f1d33b465bb557690c871d36b7":{
      "scriptId":"u58"},
    "f99d1084102c4875aad62d37693b9679":{
      "scriptId":"u59"},
    "96934760bcb24d23b3e8fc1056759654":{
      "scriptId":"u60"},
    "4e03ffc86b82463a942cacb0f1fec34b":{
      "scriptId":"u61"},
    "603a4b206ada400ab7e386d28d133341":{
      "scriptId":"u62"},
    "1288a2f09744491db3de5319625402a4":{
      "scriptId":"u63"},
    "0ab1d9a70501412fa94c5eeb0890c69d":{
      "scriptId":"u64"},
    "dc190017f256495ab82bdd053dc4eb15":{
      "scriptId":"u65"},
    "1ca535da749649aaa63a729d58404eda":{
      "scriptId":"u66"},
    "06804e2687344ac98c0e947302b12008":{
      "scriptId":"u67"},
    "cbc429bcce944dc98ed5aec001d78b30":{
      "scriptId":"u68"},
    "b01452bc9a794c68898ac4612d8db70f":{
      "scriptId":"u69"}}});