$axure.loadCurrentPage({
  "url":"success.html",
  "generationDate":new Date(1422951640550.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"35119a3b00d7456ea0259b547c37c796",
    "type":"Axure:Page",
    "name":"success",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da19ae5411b34e55aaa5698b583bf113",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1349,
              "height":710}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b12b30dbf8be4f7bafb5a47904da03e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1349,
                  "height":710}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u0.png"}},
{
          "id":"dfbbe251a6664ff29c0334deddc8a037",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x4CFFFF99},
            "location":{
              "x":173,
              "y":290},
            "size":{
              "width":685,
              "height":301},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed",
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6479d6f7e22c40cbaa51ab9bbbb5fae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x4CFFFF99},
                "location":{
                  "x":173,
                  "y":290},
                "size":{
                  "width":685,
                  "height":301},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed",
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u2.png"}},
{
          "id":"01ad193ccf1c47799634d4efadd07a37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":760},
            "size":{
              "width":1330,
              "height":2364}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d4a8bf0e3d4d388255f219fa17eeb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":760},
                "size":{
                  "width":1330,
                  "height":2364}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u8.png"}},
{
          "id":"33b45665241043e38dd8447d5030d8ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1349,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e7b2025d5644762a6802aa1a6c96253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1349,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u2.png"}},
{
          "id":"185b4594f029446c91dd602ce035a894",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":340,
              "y":0},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88699568c1fa4a73829ffe426caf1052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":340,
                  "y":0},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6e85c7bfcbc411cb3e16d0747cd7fc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":110},
            "size":{
              "width":300,
              "height":564}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74c3fc6f95184c6aa0a4e50214bd9dee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":110},
                "size":{
                  "width":300,
                  "height":564}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u10.png"}},
{
          "id":"2b823e68d9f64aecaf97ee71da7794a5",
          "label":"轮播图",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":964,
              "y":169},
            "size":{
              "width":206,
              "height":365}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 轮播图 到 Next 向左滑动 out 500ms 向左滑动 in 500ms 自动循环 循环间隔 3000 毫秒",
                      "panelsToStates":[{
                          "panelPath":["2b823e68d9f64aecaf97ee71da7794a5"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b742c3188cb84887a0ab74010fa52664",
              "label":"第1张轮播图",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"248fc2dca5b34a2ea8d420e191caa4f0",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":206,
                      "height":365}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f6d091a8ae44833b71a9ee7bdd5f575",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":206,
                          "height":365}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u13.png"}},
{
                  "id":"275af021d996462aa2050c2bf64fd64e",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62549f9002ce4015a11853f09ef3aa9d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u15.png"}},
{
                  "id":"26ade457440b40999a025013f24a8b04",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":87,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ca52e85c8f04ac596bbd23b18c8e2f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":87,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"f9d5a529aaf54d1fac8e70777264738f",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":111,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f9e6ca07e5fb4297967e6aa24753e063",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":111,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"9dc0d2177ae2416da4ab779ecf82d7dd",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"216882e48e334702b0f6e2a55951aa4a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"c7fdf9378a904e848c060b6a769d71da",
              "label":"第2张轮播图",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"af470bab1b694d36bf4bdd589b4d9168",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":206,
                      "height":365}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a9979eb2083487192cc5270dbbc973f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":206,
                          "height":365}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u23.png"}},
{
                  "id":"91cfb743ec504c7a8aac65c889a1096f",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19a31df4976e4c5a8c716a83b46990d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"956991a890f5421b8fbfefca48459f54",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":87,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"afe81e2acf1a46fd9656edc5d51b56b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":87,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u15.png"}},
{
                  "id":"a9bd3a37111e4a9882a883718aaee1bd",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":111,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38790a715e7a4d1190f9fe1997e9fa55",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":111,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"391246f6a2424a9a89bad5957a7bb128",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7746e443fce94148b1b7b6ed9d765c4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"553c1f450f9b4995b9aa9fcc1be1d8a3",
              "label":"第3张轮播图",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"027ef753bc884d47adaba645d96f7df4",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":206,
                      "height":365}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ba9c8abec614ed6badfb8b2228126f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":206,
                          "height":365}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u33.png"}},
{
                  "id":"f3aed390139447228408ec7d88ecdbbc",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57e26d11bd014c0fadeda24ae33fed6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"c7583aa044af47b599c8d97692e9f9e6",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":87,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1faf2fa862745dca0d31d300ed54a07",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":87,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"9df246ab6d0a42b5a4c5e4fcea7f69e5",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":111,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12c03f30b9534eadb458057ea4e277cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":111,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u15.png"}},
{
                  "id":"5ab6329983464a3e98fa25c8277848fc",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c1b2120cff1407ea4dbbd1603dd6d71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"44c0121bf4d2420eb1705863311ef246",
              "label":"第4张轮播图",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f02b799aeda046b1b1c4c711401f2baa",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":3,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":206,
                      "height":365}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1d22064037e4c01a15f0f58d1f41839",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":206,
                          "height":365}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u43.png"}},
{
                  "id":"60f1bfde2f8742a8a9bce96f235618cf",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1424209c0cdf4ee891a9661d3c0f6047",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"2f1a5fbc4eed493bb38ef3c6d15869d7",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":87,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9b800bf2473441f09dffe0d67520c7ac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":87,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"8b8c97d8115b4f419cc3b2dc620d40d0",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":111,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd48c4803635433d98df6d3870d83309",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":111,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u17.png"}},
{
                  "id":"84475fdc8e6846ae8efad7f77478a134",
                  "label":"",
                  "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":350},
                    "size":{
                      "width":8,
                      "height":8},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f79d42fc40dc4a2ca83ab4f20ee2f538",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2b823e68d9f64aecaf97ee71da7794a5",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":350},
                        "size":{
                          "width":8,
                          "height":8},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/success/u15.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"614f187caae24cb3b3fc9037a87b25bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"36px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "location":{
              "x":421,
              "y":110},
            "size":{
              "width":185,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20d3ce2a54fc47ceb2c0fa813f0d3eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"36px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "location":{
                  "x":421,
                  "y":110},
                "size":{
                  "width":185,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"898aa28c6ab343bbbdbc8c9b305202a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "location":{
              "x":220,
              "y":317},
            "size":{
              "width":412,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a20667cd77954c37a9b1b1b8a247d359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "location":{
                  "x":220,
                  "y":317},
                "size":{
                  "width":412,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99676be793674d4d805c65b606b7b2fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":220,
              "y":370},
            "size":{
              "width":170,
              "height":177},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea15009dbc93415c9ad472e7b08b1951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":220,
                  "y":370},
                "size":{
                  "width":170,
                  "height":177},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/u57.png"}},
{
          "id":"61a92a97c66e4010973de79712cbb9f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":387},
            "size":{
              "width":120,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32a637620e94a0db2de032abd0590c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":387},
                "size":{
                  "width":120,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page1/u62.png"}},
{
          "id":"1d6c3006ec6a4bd29fedb9dc464690e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":250,
              "y":517},
            "size":{
              "width":115,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7812fadccc9f4ed4989d3c4275427426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":517},
                "size":{
                  "width":115,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b01a87c9f659466f82873548418de6d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":461,
              "y":387},
            "size":{
              "width":123,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa1acf1186e4480a3752dcc133ef284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":461,
                  "y":387},
                "size":{
                  "width":123,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b64a9d36288c45e9bd3afd5ee9fe49f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":461,
              "y":437},
            "size":{
              "width":123,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195d903a4a2e43bbb7e2fe546afabd68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":461,
                  "y":437},
                "size":{
                  "width":123,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92455e252e574c29b335e338d3ca7285",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":642,
              "y":437},
            "size":{
              "width":123,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cacbcfa6de04ba9820f4f0c60e3736f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":642,
                  "y":437},
                "size":{
                  "width":123,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69e0311c5d2d40e08fae15e0e840306d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":642,
              "y":387},
            "size":{
              "width":109,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c4867646f7048c4962889165adca58d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":642,
                  "y":387},
                "size":{
                  "width":109,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bdcdf36bb5f47c4a96a7015facf34b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":613,
              "y":497},
            "size":{
              "width":180,
              "height":52},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a30c20a5e832490c8fbba13e058f74bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":613,
                  "y":497},
                "size":{
                  "width":180,
                  "height":52},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 image2 展开/收起 部件 向下",
                      "objectsToFades":[{
                          "objectPath":["3b75b6b6d6894b7e8c0f4ba5ecff1e78"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"compress",
                              "vertical":true,
                              "compressEasing":"none",
                              "compressDuration":500}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 image2 展开/收起 部件 向下",
                      "objectsToFades":[{
                          "objectPath":["3b75b6b6d6894b7e8c0f4ba5ecff1e78"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"compress",
                              "vertical":true,
                              "compressEasing":"none",
                              "compressDuration":500}}}]}]}]}},
          "images":{
            "normal~":"images/success/u71.png"}},
{
          "id":"3b75b6b6d6894b7e8c0f4ba5ecff1e78",
          "label":"image2",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":613,
              "y":549},
            "size":{
              "width":180,
              "height":161},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"619cec1197304654b7599637395697f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":613,
                  "y":549},
                "size":{
                  "width":180,
                  "height":161},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/image2_u73.png"}},
{
          "id":"2fbadec481234a93a28ead53721716ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":497},
            "size":{
              "width":179,
              "height":50},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92d36e25ba724816a154b7ecf98d241e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":497},
                "size":{
                  "width":179,
                  "height":50},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 image1 展开/收起 部件 向下",
                      "objectsToFades":[{
                          "objectPath":["05b1c6cbd3ec4c2698277e813e8f896b"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"compress",
                              "vertical":true,
                              "compressEasing":"none",
                              "compressDuration":500}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 image1 展开/收起 部件 向下",
                      "objectsToFades":[{
                          "objectPath":["05b1c6cbd3ec4c2698277e813e8f896b"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"compress",
                              "vertical":true,
                              "compressEasing":"none",
                              "compressDuration":500}}}]}]}]}},
          "images":{
            "normal~":"images/success/u75.png"}},
{
          "id":"05b1c6cbd3ec4c2698277e813e8f896b",
          "label":"image1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":424,
              "y":547},
            "size":{
              "width":179,
              "height":74},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ef0e2d5fcce48e08985ca538c5012ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":424,
                  "y":547},
                "size":{
                  "width":179,
                  "height":74},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/success/image1_u77.png"}},
{
          "id":"0367866fef7d41c98b882b919e366075",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":173,
              "y":190},
            "size":{
              "width":685,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69b2400563894edf8873f4e6d3921dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":190},
                "size":{
                  "width":685,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f82529720d14dd6955adc02e4dd14e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":173,
              "y":222},
            "size":{
              "width":167,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"710f44a7798742e1b51836c3eddbb756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":222},
                "size":{
                  "width":167,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bff54fab9d3c4190bb4a9965cc147d8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":340,
              "y":222},
            "size":{
              "width":122,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"403105a6824548fc82f20895c9c2f66f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":340,
                  "y":222},
                "size":{
                  "width":122,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 manage",
                      "target":{
                        "targetType":"page",
                        "url":"manage.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "da19ae5411b34e55aaa5698b583bf113":{
      "scriptId":"u0"},
    "b12b30dbf8be4f7bafb5a47904da03e4":{
      "scriptId":"u1"},
    "dfbbe251a6664ff29c0334deddc8a037":{
      "scriptId":"u2"},
    "6479d6f7e22c40cbaa51ab9bbbb5fae4":{
      "scriptId":"u3"},
    "01ad193ccf1c47799634d4efadd07a37":{
      "scriptId":"u4"},
    "72d4a8bf0e3d4d388255f219fa17eeb3":{
      "scriptId":"u5"},
    "33b45665241043e38dd8447d5030d8ba":{
      "scriptId":"u6"},
    "3e7b2025d5644762a6802aa1a6c96253":{
      "scriptId":"u7"},
    "185b4594f029446c91dd602ce035a894":{
      "scriptId":"u8"},
    "88699568c1fa4a73829ffe426caf1052":{
      "scriptId":"u9"},
    "f6e85c7bfcbc411cb3e16d0747cd7fc9":{
      "scriptId":"u10"},
    "74c3fc6f95184c6aa0a4e50214bd9dee":{
      "scriptId":"u11"},
    "2b823e68d9f64aecaf97ee71da7794a5":{
      "scriptId":"u12"},
    "248fc2dca5b34a2ea8d420e191caa4f0":{
      "scriptId":"u13"},
    "0f6d091a8ae44833b71a9ee7bdd5f575":{
      "scriptId":"u14"},
    "275af021d996462aa2050c2bf64fd64e":{
      "scriptId":"u15"},
    "62549f9002ce4015a11853f09ef3aa9d":{
      "scriptId":"u16"},
    "26ade457440b40999a025013f24a8b04":{
      "scriptId":"u17"},
    "1ca52e85c8f04ac596bbd23b18c8e2f8":{
      "scriptId":"u18"},
    "f9d5a529aaf54d1fac8e70777264738f":{
      "scriptId":"u19"},
    "f9e6ca07e5fb4297967e6aa24753e063":{
      "scriptId":"u20"},
    "9dc0d2177ae2416da4ab779ecf82d7dd":{
      "scriptId":"u21"},
    "216882e48e334702b0f6e2a55951aa4a":{
      "scriptId":"u22"},
    "af470bab1b694d36bf4bdd589b4d9168":{
      "scriptId":"u23"},
    "2a9979eb2083487192cc5270dbbc973f":{
      "scriptId":"u24"},
    "91cfb743ec504c7a8aac65c889a1096f":{
      "scriptId":"u25"},
    "19a31df4976e4c5a8c716a83b46990d5":{
      "scriptId":"u26"},
    "956991a890f5421b8fbfefca48459f54":{
      "scriptId":"u27"},
    "afe81e2acf1a46fd9656edc5d51b56b6":{
      "scriptId":"u28"},
    "a9bd3a37111e4a9882a883718aaee1bd":{
      "scriptId":"u29"},
    "38790a715e7a4d1190f9fe1997e9fa55":{
      "scriptId":"u30"},
    "391246f6a2424a9a89bad5957a7bb128":{
      "scriptId":"u31"},
    "7746e443fce94148b1b7b6ed9d765c4e":{
      "scriptId":"u32"},
    "027ef753bc884d47adaba645d96f7df4":{
      "scriptId":"u33"},
    "2ba9c8abec614ed6badfb8b2228126f5":{
      "scriptId":"u34"},
    "f3aed390139447228408ec7d88ecdbbc":{
      "scriptId":"u35"},
    "57e26d11bd014c0fadeda24ae33fed6c":{
      "scriptId":"u36"},
    "c7583aa044af47b599c8d97692e9f9e6":{
      "scriptId":"u37"},
    "f1faf2fa862745dca0d31d300ed54a07":{
      "scriptId":"u38"},
    "9df246ab6d0a42b5a4c5e4fcea7f69e5":{
      "scriptId":"u39"},
    "12c03f30b9534eadb458057ea4e277cc":{
      "scriptId":"u40"},
    "5ab6329983464a3e98fa25c8277848fc":{
      "scriptId":"u41"},
    "3c1b2120cff1407ea4dbbd1603dd6d71":{
      "scriptId":"u42"},
    "f02b799aeda046b1b1c4c711401f2baa":{
      "scriptId":"u43"},
    "b1d22064037e4c01a15f0f58d1f41839":{
      "scriptId":"u44"},
    "60f1bfde2f8742a8a9bce96f235618cf":{
      "scriptId":"u45"},
    "1424209c0cdf4ee891a9661d3c0f6047":{
      "scriptId":"u46"},
    "2f1a5fbc4eed493bb38ef3c6d15869d7":{
      "scriptId":"u47"},
    "9b800bf2473441f09dffe0d67520c7ac":{
      "scriptId":"u48"},
    "8b8c97d8115b4f419cc3b2dc620d40d0":{
      "scriptId":"u49"},
    "fd48c4803635433d98df6d3870d83309":{
      "scriptId":"u50"},
    "84475fdc8e6846ae8efad7f77478a134":{
      "scriptId":"u51"},
    "f79d42fc40dc4a2ca83ab4f20ee2f538":{
      "scriptId":"u52"},
    "614f187caae24cb3b3fc9037a87b25bb":{
      "scriptId":"u53"},
    "20d3ce2a54fc47ceb2c0fa813f0d3eac":{
      "scriptId":"u54"},
    "898aa28c6ab343bbbdbc8c9b305202a8":{
      "scriptId":"u55"},
    "a20667cd77954c37a9b1b1b8a247d359":{
      "scriptId":"u56"},
    "99676be793674d4d805c65b606b7b2fb":{
      "scriptId":"u57"},
    "ea15009dbc93415c9ad472e7b08b1951":{
      "scriptId":"u58"},
    "61a92a97c66e4010973de79712cbb9f3":{
      "scriptId":"u59"},
    "c32a637620e94a0db2de032abd0590c3":{
      "scriptId":"u60"},
    "1d6c3006ec6a4bd29fedb9dc464690e0":{
      "scriptId":"u61"},
    "7812fadccc9f4ed4989d3c4275427426":{
      "scriptId":"u62"},
    "b01a87c9f659466f82873548418de6d8":{
      "scriptId":"u63"},
    "aaa1acf1186e4480a3752dcc133ef284":{
      "scriptId":"u64"},
    "b64a9d36288c45e9bd3afd5ee9fe49f4":{
      "scriptId":"u65"},
    "195d903a4a2e43bbb7e2fe546afabd68":{
      "scriptId":"u66"},
    "92455e252e574c29b335e338d3ca7285":{
      "scriptId":"u67"},
    "6cacbcfa6de04ba9820f4f0c60e3736f":{
      "scriptId":"u68"},
    "69e0311c5d2d40e08fae15e0e840306d":{
      "scriptId":"u69"},
    "4c4867646f7048c4962889165adca58d":{
      "scriptId":"u70"},
    "5bdcdf36bb5f47c4a96a7015facf34b5":{
      "scriptId":"u71"},
    "a30c20a5e832490c8fbba13e058f74bc":{
      "scriptId":"u72"},
    "3b75b6b6d6894b7e8c0f4ba5ecff1e78":{
      "scriptId":"u73"},
    "619cec1197304654b7599637395697f8":{
      "scriptId":"u74"},
    "2fbadec481234a93a28ead53721716ce":{
      "scriptId":"u75"},
    "92d36e25ba724816a154b7ecf98d241e":{
      "scriptId":"u76"},
    "05b1c6cbd3ec4c2698277e813e8f896b":{
      "scriptId":"u77"},
    "3ef0e2d5fcce48e08985ca538c5012ec":{
      "scriptId":"u78"},
    "0367866fef7d41c98b882b919e366075":{
      "scriptId":"u79"},
    "69b2400563894edf8873f4e6d3921dfb":{
      "scriptId":"u80"},
    "4f82529720d14dd6955adc02e4dd14e5":{
      "scriptId":"u81"},
    "710f44a7798742e1b51836c3eddbb756":{
      "scriptId":"u82"},
    "bff54fab9d3c4190bb4a9965cc147d8c":{
      "scriptId":"u83"},
    "403105a6824548fc82f20895c9c2f66f":{
      "scriptId":"u84"}}});