$axure.loadCurrentPage({
  "url":"update.html",
  "generationDate":new Date(1422951640661.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a09468eae14948a6ad4f7486c124ad9d",
    "type":"Axure:Page",
    "name":"update",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"227de1a76f0e47f7923ed102d37a004c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1330,
              "height":1932}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90d5e95f15764fd389bc8468788ca28e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1330,
                  "height":1932}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/update/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "227de1a76f0e47f7923ed102d37a004c":{
      "scriptId":"u0"},
    "90d5e95f15764fd389bc8468788ca28e":{
      "scriptId":"u1"}}});